idea.config.path=C:/Users/User/IdeaProjects/configiq_airflow_kafka_connect/.intellijPlatform/sandbox/PY-2025.1/config
idea.system.path=C:/Users/User/IdeaProjects/configiq_airflow_kafka_connect/.intellijPlatform/sandbox/PY-2025.1/system
idea.plugins.path=C:/Users/User/IdeaProjects/configiq_airflow_kafka_connect/.intellijPlatform/sandbox/PY-2025.1/plugins
idea.log.path=C:/Users/User/IdeaProjects/configiq_airflow_kafka_connect/.intellijPlatform/sandbox/PY-2025.1/log
